language: node_js
node_js:
- '8'
sudo: true
dist: trusty
addons:
  chrome: stable
jobs:
  include:
  - stage: build
    script: npm run build
deploy:
  provider: npm
  email: info@qminderapp.com
  api_key:
    secure: YfD6kgSsX8qwx/1hV5ul51qO40UsQ/VUDLO7JCl+pZutTkvrk+d61U2+RgB1b7h2IkCHHBI2yKSnmvV+eEobvABRwxtCH0QfmctJAXHFCeFPJ7f+KRSXGFcQqxVgBtej2jE6k6VMuAh+/8lK8740RWOyP99hy01m1FBPTexLtXQ=
  on:
    tags: true
    repo: Qminder/javascript-api
  skip_cleanup: true
