language: node_js
node_js:
- '8'
sudo: true
dist: trusty
addons:
  chrome: stable
jobs:
  include:
  - stage: build
    script: npm run build
deploy:
  provider: npm
  email: info@qminderapp.com
  api_key:
    secure: cm3Z2rYhfz820mV5q+vRC4/ap9ljlpOgExUUV1Q8Ub54d60NzogFnKT96sd7QPVjEMTbDbZNEtIg1QaydCMpc6jTnZiWFbEP5hyqKLb1vgkWSnLsiMeDUcba0r2MuJBkjQKbIiXqGCuuwEtlVJcE2wV16qv1rsFRfYbZeHaWKm8=
  on:
    tags: true
    repo: Qminder/javascript-api
  skip_cleanup: true
