language: node_js
node_js:
- '8'
sudo: true
dist: trusty
addons:
  chrome: stable
jobs:
  include:
  - stage: build
    script: npm run build
deploy:
  provider: npm
  email: info@qminderapp.com
  api_key:
    secure: epHID6OvNKSt0P4u9YSQgjpJxT+xjvFYzD3CzmUx78Y5ySzQM5CxBOIsoVSvQDrl08UT6nukgMInL3MhQ9aWxl/JNDDXwEGoYJ4nAkydSBjS5T6qWxG7Awb4Opb65YC258B0BReW6nPtkCUqTUgCy9oK47TpjGK4ow4nwhPp0Ss=
  on:
    tags: true
    repo: Qminder/javascript-api
  skip_cleanup: true
