language: node_js
node_js:
- 0.1
sudo: true
dist: trusty

addons:
  chrome: stable
before_script:
- npm install -g grunt-cli
after_success:
- test ${TRAVIS_BRANCH} = master && sudo pip install boto && python deploy_s3.py
deploy:
  provider: npm
  email: info@qminderapp.com
  api_key:
    secure: I+dkutiDxxPHg6v6mUSnoOUjJKi9fTdgFqqukvcxkq5r7YDVUFyIND7oifd66eVOI1Fcx92JDIIEnyxZo264DlbvzlM14aLOIJjvVvYsaAFOKq4K4mvzL47t9D+T51mOKVeKQnH8QlPj+rA+FIrMkIXn9NpynKk2HEIBBZ2k8ug=
  on:
    tags: true
    repo: Qminder/javascript-api
