export { TicketCreationParameters } from '../lib/model/ticket-creation-parameters.js';
export { GraphqlResponse } from '../lib/model/graphql-response.js';
export { ConnectionStatus } from '../lib/model/connection-status.js';
export { Desk } from '../lib/model/desk.js';
export { Device } from '../lib/model/device.js';
export { Id } from '../lib/model/id.js';
export { Line } from '../lib/model/line.js';
export { Location } from '../lib/model/location.js';
export { TicketExtra } from '../lib/model/ticket-extra.js';
export { TicketLabel } from '../lib/model/ticket-label.js';
export { Ticket } from '../lib/model/ticket.js';
export { User } from '../lib/model/user.js';
export { Webhook } from '../lib/model/webhook.js';
export { SimpleError } from '../lib/model/errors/simple-error.js'
export { ComplexError } from '../lib/model/errors/complex-error.js'
