on: push
name: Test on push
jobs:
  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install --frozen-lockfile
      - run: yarn jest --coverage
      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          verbose: true
