on: push
name: Lint

jobs:
  prettier:
    name: Check prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
      - name: Install Deps
        run: |
          yarn install --immutable
      - name: Prettier check
        run: |
          yarn run lint-prettier
  eslint:
    name: Check eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
      - name: Install Deps
        run: |
          yarn install --immutable
      - name: Eslint check
        run: |
          yarn run lint-eslint
