on: push
name: Test on push

defaults:
  run:
    working-directory: ./packages/javascript-api

jobs:
  test:
    name: Test (JSDOM)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
      - name: Install Deps
        run: yarn install --immutable
      - name: Run tests (browser)
        run: yarn test
  test_node:
    name: Test (Node.js)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
      - name: Install Deps
        run: yarn install --immutable
      - name: Run tests (node)
        run: yarn test-node

  test_pack:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
      - name: Install Deps
        run: yarn install --immutable
      - name: Build the package
        run: yarn pack
