on: push
name: Test on push
jobs:
  test:
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    name: Test on NodeJS ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install Deps
        run: yarn install --immutable
      - name: Run tests (browser)
        run: yarn test
      - name: Run tests (node)
        run: yarn test-node
      - name: Build the package
        run: yarn pack
  prettier:
    name: Check prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: Install Deps
        run: |
          yarn install --immutable
      - name: Prettier check
        run: |
          yarn run lint-prettier
  eslint:
    name: Check eslint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: Install Deps
        run: |
          yarn install --immutable
      - name: Eslint check
        run: |
          yarn run lint-eslint
