on:
  release:
    types:
      - published

name: Release
jobs:
  release:
    name: Publish to NPM Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
          always-auth: true
          registry-url: https://registry.npmjs.org
      - name: Install Deps
        run: yarn install --immutable
      - name: Build Library
        run: yarn build
      - name: Publish package to NPM
        run: yarn npm publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
