on: pull_request
name: Test examples

jobs:
  build-example-graphql-events:
    name: Build Example GraphQL Events
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
      - name: Install Deps
        run: yarn install --immutable
      - name: Build
        run: yarn workspace qminder-graphql-events-example build
