name: "Test"
on:
  - push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: run tests
        run: npm run build
